import { ModeToggle } from "@/components/theme/ModeToggle";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <div className="flex justify-center items-center min-h-screen bg-gray-100 dark:bg-gray-900 p-4">
          <div>
            <ModeToggle />
          </div>
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-10 flex flex-col items-center max-w-md w-full">
            <Image
              src="/logo-stackly.png"
              alt="E-Commerce Logo"
              className="  mb-4"
              height={200}
              width={200}
            />
            <h1 className="text-4xl font-extrabold text-purple-700 dark:text-purple-400 mb-2">
              Welcome to ShopEase
            </h1>
            <p className="text-gray-600 dark:text-gray-300 mb-6 text-center">
              Sign in to access exclusive deals and manage your account.
            </p>
            <button
              className="w-full bg-purple-600 hover:bg-purple-700 dark:bg-purple-500 dark:hover:bg-purple-600 text-white font-semibold py-3 px-6 rounded-lg transition-colors duration-200 mb-2"
              onClick={() => (window.location.href = "/auth")}
            >
              Go to Login
            </button>
          </div>
        </div>
      </>
    </>
  );
}
